- name: Send request to API (create EIP)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/publicips"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  register: eip
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: eip.status == 200
  changed_when: false
  when: public_ip_address == "0.0.0.0"

- set_fact:
    public_ip_address: "{{ (eip.content|from_json)|json_query('publicip.public_ip_address') }}"
    eip_id: "{{ (eip.content|from_json)|json_query('publicip.id') }}"
  when: public_ip_address == "0.0.0.0"

- debug:
    msg: "{{ public_ip_address }}"
