- name: Lookup eip_id
  include: lookup.yml

- name: Send request to API (delete EIP)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/publicips/{{ eip_id }}"
    method: DELETE
    body_format: raw
    return_content: yes
    status_code: 200,201,202,203,204
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: eip
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: eip.status == 200 or eip.status == 201 or eip.status == 202 or eip.status == 203 or eip.status == 204
  changed_when: false

- debug:
    msg: "{{ eip }}"
